import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.css";
import { userInfo } from "os";
import * as React from "react";
import {useSession} from "next-auth/react";
import Link from 'next/link'
import {useRouter} from "next/router";



const Home: NextPage = (props) => {

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Home for</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}> Home  </h1>

          <p className={styles.description}>
            hello there 
          </p>

        
        </main>

     
      </div>
    </>
  );
};

export default Home;
